baseURL = "https://tanolis.github.io/worksheet-generator/public/"
languageCode = "en-us"
title = "Worksheet Generator"
# theme = "none"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

publishDir = "docs"